# Generated by Django 5.2.7 on 2025-10-29 08:15

import design_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='design_photo',
            field=models.ImageField(blank=True, null=True, upload_to='design_photos/', validators=[design_app.models.validate_image_size, design_app.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(upload_to='application_photos/', validators=[design_app.models.validate_image_size, design_app.models.validate_image_extension]),
        ),
    ]
